[pytest]
# Thay vì phải gõ dòng lệnh dài mỗi lần kiểm thử, ta chỉ việc gõ:
# pytest 
# Vì file pytest.ini có nhiệm vụ lưu cấu hình cho các lần kiểm thử.
filterwarnings =
    ignore::DeprecationWarning